name: Deploy  MERAKI Application 

on:
  push:
    branches: [ main ]

env:
  AZURE_VM_HOST: ${{ secrets.AZURE_VM_HOST }}
  AZURE_VM_USERNAME: ${{ secrets.AZURE_VM_USERNAME }}
  AZURE_SSH_PRIVATE_KEY: ${{ secrets.AZURE_SSH_PRIVATE_KEY }}
  ACR_LOGIN_SERVER: ${{ secrets.ACR_LOGIN_SERVER }}
  ACR_USERNAME: ${{ secrets.ACR_USERNAME }}
  ACR_PASSWORD: ${{ secrets.ACR_PASSWORD }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.AZURE_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.AZURE_VM_HOST }} >> ~/.ssh/known_hosts

    - name: Deploy Frontend
      run: |
        # SSH into VM and deploy frontend
        ssh ${{ secrets.AZURE_VM_USERNAME }}@${{ secrets.AZURE_VM_HOST }} '
          echo "Starting frontend deployment..."
          
          # Clone frontend repository (specifically the main branch with Dockerfile)
          rm -rf ~/MERAKI-FE
          git clone -b development https://github.com/TEAM-MERAKI-NAA/MERAKI-FE.git
          
          echo "Moving to repository directory..."
          cd ~/MERAKI-FE
          
          # Check if Dockerfile exists
          if [ ! -f "Dockerfile" ]; then
            echo "ERROR: Dockerfile not found in current directory"
            echo "Contents of directory:"
            ls -la
            exit 1
          fi
          
          echo "Dockerfile found, proceeding with build..."
          
          # Login to ACR
          echo "Logging in to ACR..."
          echo "${{ secrets.ACR_PASSWORD }}" | docker login ${{ secrets.ACR_LOGIN_SERVER }} -u ${{ secrets.ACR_USERNAME }} --password-stdin
          
          # Stop and remove existing containers more safely
          echo "Managing existing containers..."
          FRONTEND_CONTAINERS=$(docker ps -q --filter ancestor=${{ secrets.ACR_LOGIN_SERVER }}/immihub-fe 2>/dev/null || true)
          if [ -n "$FRONTEND_CONTAINERS" ]; then
            echo "Stopping and removing existing frontend containers"
            docker stop $FRONTEND_CONTAINERS
            docker rm $FRONTEND_CONTAINERS
          else
            echo "No existing frontend containers found"
          fi
          
          # Build and tag image
          echo "Building Docker image..."
          docker build -t immihub-fe .
          
          echo "Tagging Docker image..."
          docker tag immihub-fe ${{ secrets.ACR_LOGIN_SERVER }}/immihub-fe:latest
          
          # Push to ACR
          echo "Pushing to ACR..."
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/immihub-fe:latest
          
          # Run the container
          echo "Running the container..."
          docker run -d -p 3000:3000 ${{ secrets.ACR_LOGIN_SERVER }}/immihub-fe:latest
          
          echo "Frontend deployment completed!"
        '

    - name: Deploy Backend
      run: |
        # SSH into VM and deploy backend
        ssh ${{ secrets.AZURE_VM_USERNAME }}@${{ secrets.AZURE_VM_HOST }} '
          echo "Starting backend deployment..."
          
          # Clone backend repository
          rm -rf ~/MERAKI-BE
          git clone -b swagat-newbase https://github.com/TEAM-MERAKI-NAA/MERAKI-BE.git ~/MERAKI-BE
          
          echo "Moving to repository directory..."
          cd ~/MERAKI-BE
          
          # Try to find Dockerfile recursively
          DOCKERFILE_PATH=$(find . -name "Dockerfile" | head -1)
          
          if [ -z "$DOCKERFILE_PATH" ]; then
            echo "ERROR: Dockerfile not found in repository"
            echo "Contents of root directory:"
            ls -la
            exit 1
          fi
          
          # Extract directory path from file path
          DOCKER_DIR=$(dirname "$DOCKERFILE_PATH")
          echo "Dockerfile found at: $DOCKERFILE_PATH"
          echo "Moving to directory: $DOCKER_DIR"
          cd "$DOCKER_DIR"
          
          echo "Current directory contents:" 
          ls -la
          
          # Login to ACR
          echo "Logging in to ACR..."
          echo "${{ secrets.ACR_PASSWORD }}" | docker login ${{ secrets.ACR_LOGIN_SERVER }} -u ${{ secrets.ACR_USERNAME }} --password-stdin
          
          # Stop and remove existing containers more safely
          echo "Managing existing containers..."
          BACKEND_CONTAINERS=$(docker ps -q --filter ancestor=${{ secrets.ACR_LOGIN_SERVER }}/immihub-be 2>/dev/null || true)
          if [ -n "$BACKEND_CONTAINERS" ]; then
            echo "Stopping and removing existing backend containers"
            docker stop $BACKEND_CONTAINERS
            docker rm $BACKEND_CONTAINERS
          else
            echo "No existing backend containers found"
          fi
          
          # Build and tag image
          echo "Building Docker image..."
          docker build -t immihub-be .
          
          echo "Tagging Docker image..."
          docker tag immihub-be ${{ secrets.ACR_LOGIN_SERVER }}/immihub-be:latest
          
          # Push to ACR
          echo "Pushing to ACR..."
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/immihub-be:latest
          
          # Run the container
          echo "Running the container..."
          docker run -d -p 8000:8000 ${{ secrets.ACR_LOGIN_SERVER }}/immihub-be:latest
          
          echo "Backend deployment completed!"
        '

    - name: Health Check
      run: |
        echo "Waiting for services to start..."
        sleep 30
        
        echo "Checking frontend health..."
        curl -f http://${{ secrets.AZURE_VM_HOST }}:3000 || {
          echo "Frontend health check failed!"
          exit 1
        }
        
    

    - name: Cleanup
      if: always()
      run: |
        echo "Cleaning up SSH keys..."
        rm -f ~/.ssh/id_rsa
        echo "Deployment workflow completed."
