name: Deploy to Azure VM

on:
  push:
    branches: [ main ]  # Adjust branch name if needed
  workflow_dispatch:    # Allows manual triggering

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add host key to known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.VM_IP }} >> ~/.ssh/known_hosts

      - name: Copy deployment scripts to VM
        run: |
          scp -o StrictHostKeyChecking=no deployment/*.sh ${{ secrets.VM_USERNAME }}@${{ secrets.VM_IP }}:~
        
      - name: Make scripts executable
        run: |
          ssh ${{ secrets.VM_USERNAME }}@${{ secrets.VM_IP }} 'chmod +x ~/*.sh'
      
      - name: Create deployment configuration
        run: |
          ssh ${{ secrets.VM_USERNAME }}@${{ secrets.VM_IP }} "echo '#!/bin/bash
          # Auto-generated by GitHub Actions
          FRONTEND_REPO=\"${{ github.repository }}/frontend\"
          BACKEND_REPO=\"${{ github.repository }}/backend\"
          FRONTEND_PORT=3001
          ' > ~/deployment-config.sh"
          
      - name: Deploy frontend
        run: |
          ssh ${{ secrets.VM_USERNAME }}@${{ secrets.VM_IP }} './deploy-frontend.sh'
          
      - name: Deploy backend
        run: |
          ssh ${{ secrets.VM_USERNAME }}@${{ secrets.VM_IP }} './deploy-backend.sh'
          
      - name: Setup Nginx
        run: |
          ssh ${{ secrets.VM_USERNAME }}@${{ secrets.VM_IP }} './setup-nginx.sh'
          
      - name: Verify deployment
        run: |
          echo "Deployment completed to ${{ secrets.VM_IP }}"
          echo "Frontend available at: http://${{ secrets.VM_IP }}:3001"
          echo "Backend available at: http://${{ secrets.VM_IP }}:8000"