name: Deploy MERAKI Application

on:
  push:
    branches: [ latest-branch--updates ]

env:
  AZURE_VM_HOST: ${{ secrets.AZURE_VM_HOST }}
  AZURE_VM_USERNAME: ${{ secrets.AZURE_VM_USERNAME }}
  AZURE_SSH_PRIVATE_KEY: ${{ secrets.AZURE_SSH_PRIVATE_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.AZURE_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.AZURE_VM_HOST }} >> ~/.ssh/known_hosts

    - name: Deploy Frontend
      run: |
        # Copy frontend files to VM
        scp -r MERAKI-FE/* ${{ secrets.AZURE_VM_USERNAME }}@${{ secrets.AZURE_VM_HOST }}:~/MERAKI-FE/
        
        # SSH into VM and deploy frontend
        ssh ${{ secrets.AZURE_VM_USERNAME }}@${{ secrets.AZURE_VM_HOST }} '
          cd ~/MERAKI-FE
          docker stop $(docker ps -q --filter ancestor=ImmiHub-FE) || true
          docker rm $(docker ps -aq --filter ancestor=ImmiHub-FE) || true
          docker build -t ImmiHub-FE .
          docker run -d -p 3000:3000 ImmiHub-FE
        '

    - name: Deploy Backend
      run: |
        # Copy backend files to VM
        scp -r MERAKI-BE/* ${{ secrets.AZURE_VM_USERNAME }}@${{ secrets.AZURE_VM_HOST }}:~/MERAKI-BE/
        
        # SSH into VM and deploy backend
        ssh ${{ secrets.AZURE_VM_USERNAME }}@${{ secrets.AZURE_VM_HOST }} '
          cd ~/MERAKI-BE
          docker stop $(docker ps -q --filter ancestor=ImmiHub-BE) || true
          docker rm $(docker ps -aq --filter ancestor=ImmiHub-BE) || true
          docker build -t ImmiHub-BE .
          docker run -d -p 8000:8000 ImmiHub-BE
        '

    - name: Health Check
      run: |
        # Wait for services to start
        sleep 30
        
        # Check frontend
        curl -f http://${{ secrets.AZURE_VM_HOST }}:3000 || exit 1
        
        # Check backend
        curl -f http://${{ secrets.AZURE_VM_HOST }}:8000/health/ || exit 1

    - name: Cleanup
      if: always()
      run: |
        rm -f ~/.ssh/id_rsa 